### ISSUE TITLE
Support for LLVM 9.0

### ISSUE THREAD

**Issue by mchalupa** [staticafi/llvm2c#33]
Needed by https://github.com/staticafi/symbiotic/issues/119

**Comment by tomsik68** [comment]
LLVM 9.0 should be supported as of https://github.com/staticafi/llvm2c/commit/1cbd9407cde0ab31406967d7c09e6595c2b17e55

**Comment by mchalupa** [comment]
Great! So this issue can be closed now?

**Comment by mchalupa** [comment]
Tested, it works :)
