### ISSUE TITLE
bitcast instruction

### ISSUE THREAD

**Issue by suarezvictor** [staticafi/llvm2c#50]
There's a bug with respect to bitcast instruction: it shoudln't be cast with (float) or (unsigned int) operations: the bitcast should be a reinterpretation of the memory (i.e. corresponding to "memcpy"). If not, the compiler issues a conversion from float to interger or interger to float.

```
  %17 = bitcast float %13 to i32
  %21 = bitcast i32 %20 to float

```
Possible implementation:
```
inline unsigned int bitcast_to_uint(float a) { union _noname { float f; unsigned int i;} conv; conv.f = a; return conv.i; }
inline float bitcast_to_float(unsigned int a) { union _noname { float f; unsigned int i;} conv; conv.i = a; return conv.f; }
```

**Comment by mchalupa** [comment]
Thanks for reporting this and sorry for not re-acting. This should be fixed, I think:
https://github.com/staticafi/llvm2c/blob/e46b0ba192070c5456731c1ef256624d28c0495e/main.cpp#L21

Although it is not enabled by default for now.
